### Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Dastan",
  "surname": "Abilashomov",
  "phone": "88888",
  "password": "88888",
  "email": "boy.pacan@gmail.com"
}




### Authorization user
POST localhost:8080/auth/login
Content-Type: application/json
Accept-Language: EN

{
  "phone":"88888",
  "password": "88888"
}

### Authorization Admin
POST localhost:8080/auth/login
Content-Type: application/json

{
  "phone": "0000",
  "password": "0000"
}